### ISSUE TITLE
Suggestion: Ability to filter by mob lvl

### ISSUE THREAD

**Issue by FunkeyMonkey** [KangasZ/RadarPlugin#26]
Loving the plugin so far! is there any way to have an option to hide/filter mobs below a certain threshold and or non aggro mobs? Like if i'm running around at lvl 90 and going through an area that is lvl 1-5 mobs I don't really need to see them. An option to hide mob tags say below 10 (or adjustable) lvls of character lvl would be amazing! 

If it would be possible to have different color options for Hunt board mobs as well that would be amazing.

Thanks

**Comment by KangasZ** [comment]
I plan to work on the `level below you` check soon. Should not require too much new.

As for hunts, I don't have any list of dataids for hunt mobs. Would have to make that or find it somewhere. If you have a list of the hunts I could start separating them the way deep dungeon mobs are separated already.

**Comment by FunkeyMonkey** [comment]
That's great to hear about level below, i'll definitely see what i can do about getting a list together. One thing i did notice, not sure if it's stock or if there's a plugin i have doing this (I tried disabling a couple i thought might do this but nada) but i did see there's a special icon on their head signifying it's a hunt mob. Not sure if there's any way to read that through the plugin so it "creates" the list iteself.

![image](https://github.com/KangasZ/RadarPlugin/assets/13045972/03fb2737-d562-497a-bada-7858125a0bd1)

**Comment by KangasZ** [comment]
Might just be a game feature lol. No clue

**Comment by KangasZ** [comment]
The level-based rendering has been completed. There is now an option to have a separate config for mobs some levels below you. I had a few ideas for a more in-depth implementation but didn't want to make it too complex atm. This does not work for eureka or deep dungeons as of now.

Hunts still pending more investigation. It doesn't look like the mobs have any special flags, and other plugins (specifically HuntHelper) does it by a manually created list of hunts. Could simply copy it over, but still looking into how that can best be done.

**Comment by FunkeyMonkey** [comment]
Awesome, yeah i was going to suggest to look at HuntHelper as i was using that as well. I think your plugin if able to mark the mobs different along with Helper would be a great combo.

**Comment by KangasZ** [comment]
#28
