### ISSUE TITLE
Collection of Deep Dungeon IDs for Categorizing and Color-Coding

### ISSUE THREAD

**Issue by XIV-Enjoyer** [KangasZ/RadarPlugin#4]
Hello, I'm glad to see there's finally a Radar built for Dalamud. I've always used MMOMinion's for Deep Dungeon stuff, to make my own life easier. :)

Something I've done was utilizing the custom lists, to color code and give custom names for all the objects that I'd need to keep track of with the radar.

So I'll just dump it all below, I apologize if it's a lot, but I like what I see with this tool and I hope this info can help you out.

## Deep Dungeon Maps
The order of these IDs are the order of the floor sets. As you can see HoH is weird where it starts alternating after 21-30.
| Map Name | Map IDs|
|---| -------|
| Palace of the Dead | 561, 562, 563, 564, 565, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605 |
| Heaven-on-High | 770, 771, 772, 782, 773, 783, 774, 784, 775, 785 |

## Treasure Coffers
I would have coffers named separately and color coded to be able to quickly identify them.
The reason why there's so many Bronze Coffer IDs is because the drops change depending on the floor sets, but that's for another time.
| ID | Name | Type | Maps | Extra Notes |
| - | -- | - | - | ---- |
| 2007358 | Gold Coffer | EventObj | All |
| 2007357 | Silver Coffer | EventObj | All |
| 782, 783, 784, 785, 786, 787, 788, 789, 790, 802, 803, 804, 805 | Bronze Coffer | EventObj | PotD | Phoenix Down, Potion, Hi-Potion, Mega-Potion, X-Potion, Max-Potion, Gelmorran Potsherd | 
| 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049 | Bronze Coffer | EventObj| HoH| Phoenix Down, Super-Potion, Empyrean Potsherd | 
| 2006020 | Bronze Coffer (Mimic) | EventObj | All | This is the only disguised Mimic coffer detectable client side. |
| 2007542 | Accursed Hoard | EventObj | All | Only visible after using an Intuition. |

## Passage and Return Nodes
I would personally color code Passage node as green, so I could identify where the exit is.
| ID | Name | Type | Maps |
| - | -- | - | - |
| 2007187 | Cairn of Return | EventObj | PotD |
| 2007188 | Cairn of Passage | EventObj | PotD |
| 2009506 | Beacon of Return | EventObj | HoH |
| 2009507 | Beacon of Passage | EventObj | HoH |

## Traps
When revealed with a Pomander of Sight, it's useful to see what traps are available, especially when it comes to using Landmines for mob damage, or Luring for additional kills.
| ID | Name | Type | Maps | Extra Notes |
| - | -- | - | - | ---- |
| 2007182 | Landmine | EventObj | All | |
| 2007183 | Luring | EventObj | All | |
| 2007184 | Enfeebling | EventObj | All | Debuff: Enervation |
| 2007185 | Impeding | EventObj | All | Debuff: Pacification, Silence |
| 2007186 | Toading | EventObj | PotD | Debuff: Toad |
| 2009504 | Odder | EventObj | HoH | Debuff: Odder |

## Mimics and Mandragoras
After using an Alteration, being able to see what spawned helps with my next plan of action
| ID | Name | Type | Maps | Extra Notes |
| - | -- | - | - | ---- |
| 2566 | Mimic | BattleNpc | PotD | Applies to all colors. |
| 7392 | Quivering Coffer| BattleNpc  | HoH | Bronze |
| 7393 | Quivering Coffer| BattleNpc  | HoH | Silver |
| 7394 | Quivering Coffer| BattleNpc  | HoH | Gold |
| 5041 | Pygmaioi| BattleNpc  | PotD | |
| 7610 | Korrigan| BattleNpc  | HoH | |

## PotD Special Undead
There are special undead mobs that can spawn on ceratin floor sets, they give a large points bonus. I'd color code them separately from the regular mobs.
| ID | Name | Type | Floor Set | Identity |
| - | -- | - | - | ---- |
| 5049 | spear-shaking adventurer | BattleNpc | 11-20 | E'manafa |
| 5048 | staff-spinning adventurer | BattleNpc | 11-20 | Kikina |
| 5047 | sword-swinging adventurer | BattleNpc | 11-20 | Dolorous |
| 5050 | Ishgardian pikeman | BattleNpc | 21-30 | Janremi |
| 5052 | frenzied freebooter | BattleNpc | 21-30 | Baenryss |
| 5051 | roughspun ruffian | BattleNpc | 21-30 | Garibald |
| 5053 | Immortal Flame | BattleNpc | 31-40 | Jakys Ryder |
| 5046 | Duskwight lancer | BattleNpc | 41-50 | Foulques |
| 5290 | moldering merchant | BattleNpc | 51-60 | Ungust |
| 5291 | blackening marketeer | BattleNpc | 51-60 | Black Marketeer |
| 5293 | bloated archer | BattleNpc | 61-70 | Satzfloh |
| 5292 | bloated conjurer | BattleNpc | 61-70 | Una Tayuun |
| 5294 | bloated pugilist | BattleNpc | 61-70 | Percevains |
| 5295 | emaciated engineer | BattleNpc | 71-80 | Hummingway |
| 5296 | putrid plutocrat | BattleNpc | 71-80 | Eolande |
| 5297 | insentient inquisitor | BattleNpc | 81-90 | Guillame |
| 5298 | necrose knight | BattleNpc | 81-90 | Chlodebaimt |
| 5283 | mortifying magnate | BattleNpc | 91-100 | Teledji Adeledji |
| 5284 | corrupted centurion | BattleNpc | 101-110 | Black Eft Pilot |
| 5285 | gangrenous gigant | BattleNpc | 121-130 | Ouranos |
| 5286 | half-cracked captain | BattleNpc | 131-140 | Madison |
| 5287 | sunken captain | BattleNpc | 151-160 | Symond |
| 5288 | flyblown praefectus | BattleNpc | 161-170 | Rhitahtyn |
| 5289 | jaundiced tribunus | BattleNpc | 181-190 | Livia |

## HoH Auspices
There are 3 divine animals that rarely wander about and can grant a buff.
| ID | Name | Type | Buff | Effect |
| - | -- | - | - | ---- |
| 7396 | Komainu | BattleNpc | Komainu's Favor | Damage dealt is increased. |
| 7397 | Inugami | BattleNpc | Inugami's Favor | Damage taken is decreased. |
| 7398 | Senri | BattleNpc | Senri's Favor | Regenerating HP over time. |

**Comment by KangasZ** [comment]
I presume the content id's are all equal to DataId? Seems to be the case from what I had, just want to make sure.

I've been intending to write custom mob color and renames for a while. One of the original uses of the beta of the plugin was finding eureka fairies. The per-mob config was scrapped mainly due to swapping from NameIds to DataIds early in development.

I can look into creating custom zones and having preset categories, perhaps a set enum that can be configured against, ie

- Special Mobs (Special undead)
- Auspice
- Korrigan + Pygmaioi
- Traps
- Cairn + Beacons
- Chests Categories =>Gold - Silver - Bronze (This would apply to colored mimics aswell(?))

Where each enum value would have a custom color associated with it.

Then as a general feature improvement, custom colors and renames for individual mobs/DataIds, which would override any preset.

Most of the traps and cairn/beacons were already included in a custom rename list, albiet not recolored, but I added a few that I didn't have already.

The one HoH Auspice I saw was a BattleNpc. No clue if this is accurate as I was not focused on development at the time.

**Comment by XIV-Enjoyer** [comment]
Ah, it probably is data ID. I just know MMOMinion called it "Content ID", so that's where I got that from.

https://github.com/xivapi/ffxiv-datamining/blob/master/csv/BNpcName.csv

Oh and you're right, the Auspices are BattleNpcs also. I'll edit that in.

**Comment by XIV-Enjoyer** [comment]
Okay, I updated the original post with the corrections. All in all, thank you very much for this radar.  And I appreciate taking the time to look at all of this.  Looking forward to the custom overrides too, that's a great thing feature to have.

**Comment by KangasZ** [comment]
Initial DataId based color customization has been pushed out. Should be available by updating the plugin. Change the colors in the utility -> load current mobs menu.

**Comment by XIV-Enjoyer** [comment]
Hi there, many thanks for it. I've been checking it out this morning. Just a couple of things I noticed.

Objects without a name (like Hoard and Traps) need "Nameless" enabled.

![ffxiv_dx11_pePmJhbfcJ](https://user-images.githubusercontent.com/120745302/208246004-5c04e8d4-d46c-4fc0-b946-8c36b294ec66.gif)

Bronze Coffers aren't displaying unless "Loot" is enabled, but even then it's only saying "Treasure Coffer" and not "Bronze Coffer". I realized the regular Bronze Coffers aren't "EventObj" but they're "Treasure". I edited the original post to reflect that. (That explains why they behave differently than Silver/Gold Chests, like how you can open them while transformed)

![ffxiv_dx11_httCYAHv3G](https://user-images.githubusercontent.com/120745302/208245872-0cd7444f-6fdd-41ef-bb28-fb9b4c410952.gif)

**Comment by KangasZ** [comment]
Remainder of the bronze coffers listed were added. BA/DD objects now take precedent over any other setting and independant of object type (fixing nameless).

**Comment by XIV-Enjoyer** [comment]
Awesome thank you. I think I did the edit suggestion right to fix the Toading/Odder Trap names.

Oh and when Eureka Orthos comes out, I'll be sure to try to get the IDs for all the new stuff ASAP. But that's some months away (I personally can't wait to tackle that).

**Comment by KangasZ** [comment]
The larger part of this feature including seperate color schemes for different types of mobs/objects has been released. Considering this feature request done.
