### ISSUE TITLE
Trap Visibility 

### ISSUE THREAD

**Issue by PayDQueso** [KangasZ/RadarPlugin#9]
How this function work? i have it enable but doesnt show the traps

**Comment by KangasZ** [comment]
Traps are only visible once they are revealed client-side. If you want a helper with deep dungeon trap finding, I'll refer you to another plugin called Deep Dungeon Helper: `https://raw.githubusercontent.com/Speshkitty/DalamudPlugins/main/repo.json`

There is no way around this as the object simply is not sent to the client until the player either hits the trap or reveals it with a sight. This is the same as with BA and DR(N/S) traps.
